services:
  - type: web
    name: ieee-rama-web
    env: node
    buildCommand: "cd backend && npm install && node reset-admin.js"
    startCommand: "cd backend && node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
      # Render proporciona automáticamente el puerto
